# Generated by Django 3.1.5 on 2021-01-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.PositiveBigIntegerField(default=0, verbose_name='balance'),
        ),
    ]
